-- Pixel Memory Couple database
-- Run this whole file in Supabase Dashboard > SQL Editor.

create table if not exists public.site_content (
  id integer primary key default 1 check (id = 1),
  couple_name text not null default 'YOU + ME ♡',
  status_title text not null default 'GOOD DAY TOGETHER! ♡',
  status_text text not null default 'MEMORIES LOADING...',
  special_date text not null default '05 / 23',
  favorite_thing text not null default 'GOING HOME TOGETHER',
  updated_at timestamptz not null default now()
);

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  emoji text not null default '💗',
  title text not null,
  memory_date text not null default '',
  story text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

insert into public.site_content (id)
values (1)
on conflict (id) do nothing;

insert into public.memories (emoji, title, memory_date, story, sort_order)
select '🌷', 'First little walk', '05/23', 'A tiny walk, a silly smile, and a pocket full of memories.', 1
where not exists (select 1 from public.memories);

insert into public.memories (emoji, title, memory_date, story, sort_order)
select '🍓', 'Sweet afternoon', '05/18', 'Shared snacks taste better when we steal bites from each other.', 2
where (select count(*) from public.memories) = 1;

insert into public.memories (emoji, title, memory_date, story, sort_order)
select '🌙', 'Late-night talk', '05/11', 'The night was quiet, but somehow we talked until it wasn’t.', 3
where (select count(*) from public.memories) = 2;

alter table public.site_content enable row level security;
alter table public.memories enable row level security;

-- Public visitors can read the couple website.
drop policy if exists "public can read site content" on public.site_content;
create policy "public can read site content"
on public.site_content for select
to anon, authenticated
using (true);

drop policy if exists "public can read memories" on public.memories;
create policy "public can read memories"
on public.memories for select
to anon, authenticated
using (true);

-- Only logged-in users can edit. For a private couple site,
-- create only your own editor account in Supabase Auth.
drop policy if exists "logged in users can insert site content" on public.site_content;
create policy "logged in users can insert site content"
on public.site_content for insert
to authenticated
with check (true);

drop policy if exists "logged in users can update site content" on public.site_content;
create policy "logged in users can update site content"
on public.site_content for update
to authenticated
using (true)
with check (true);

drop policy if exists "logged in users can insert memories" on public.memories;
create policy "logged in users can insert memories"
on public.memories for insert
to authenticated
with check (true);

drop policy if exists "logged in users can update memories" on public.memories;
create policy "logged in users can update memories"
on public.memories for update
to authenticated
using (true)
with check (true);

drop policy if exists "logged in users can delete memories" on public.memories;
create policy "logged in users can delete memories"
on public.memories for delete
to authenticated
using (true);
